# Generated by Django 4.0.10 on 2023-03-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='review_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
