# Generated by Django 4.0.10 on 2023-03-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_task_deadline_date_alter_task_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
