# Generated by Django 4.0.10 on 2023-04-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_action_action_order_alter_action_date_done_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='state_id',
            new_name='state',
        ),
    ]
