# Generated by Django 4.0.10 on 2023-04-12 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_task_id_action_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recur_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_action_description', models.CharField(blank=True, max_length=100)),
                ('r_action_name', models.CharField(max_length=80)),
                ('r_action_order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recur_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_delay', models.IntegerField(default=0, help_text='Days before / after next_period_end')),
                ('every', models.IntegerField(help_text='Paired with period_freq')),
                ('fin_year', models.IntegerField(help_text='Is this needed?')),
                ('job_name_start', models.CharField(choices=[('EOM', 'EOM'), ('EOQ', 'EOQ'), ('Pays', 'Pays')], max_length=4)),
                ('next_build_date', models.DateField(help_text='Normally calculated')),
                ('next_period_end', models.DateField(help_text='Normally calculated')),
                ('period_freq', models.CharField(choices=[('day', 'day'), ('month', 'month'), ('week', 'week')], max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.client')),
            ],
        ),
        migrations.CreateModel(
            name='Recur_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eofy', models.BooleanField(default=False)),
                ('eom', models.BooleanField(default=False)),
                ('eom_ex_eoq', models.BooleanField(default=False)),
                ('eoq', models.BooleanField(default=False)),
                ('r_task_description', models.CharField(blank=True, max_length=100)),
                ('r_task_name', models.CharField(max_length=50)),
                ('r_task_order', models.IntegerField(blank=True)),
                ('recur_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.recur_job')),
            ],
        ),
        migrations.DeleteModel(
            name='Default_action',
        ),
        migrations.DeleteModel(
            name='Default_task',
        ),
        migrations.DeleteModel(
            name='Defaults_map',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_comment',
            field=models.CharField(blank=True, help_text='For users', max_length=200),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_description',
            field=models.CharField(blank=True, help_text='Normally from default', max_length=200),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.CharField(help_text='Normally from default', max_length=25),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_order',
            field=models.IntegerField(default=0, help_text='Normally from default'),
        ),
        migrations.AlterField(
            model_name='action',
            name='date_done',
            field=models.DateField(blank=True, help_text='Set by system when user marks as done', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Set as needed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='review_date',
            field=models.DateField(blank=True, help_text='Set as needed', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(default=1, help_text='ToDo Foreign key to state and handle deletion??'),
        ),
        migrations.AddField(
            model_name='recur_action',
            name='recur_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.recur_task'),
        ),
    ]
