# Generated by Django 4.0.10 on 2023-06-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='recur_action',
            options={'verbose_name_plural': 'Recurring Actions'},
        ),
        migrations.AlterModelOptions(
            name='recur_job',
            options={'verbose_name_plural': 'Recurring Jobs'},
        ),
        migrations.AlterModelOptions(
            name='recur_task',
            options={'verbose_name_plural': 'Recurring Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, choices=[('ACT', 'Action needed'), ('AWOK    , Await OK to lodge...', 'Awok'), ('AWIN', 'Await information'), ('COMP', 'Completed'), ('FUP', 'Follow up'), ('INP', 'In progress'), ('LOD', 'Lodged - ATO to file'), ('TOI', 'To invoice')], max_length=40),
        ),
    ]
