# Generated by Django 4.0.10 on 2023-09-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_activity_options_alter_recur_action_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='jobs.task'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='jobs.task'),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.client'),
        ),
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Action needed'), (2, 'Await OK to lodge...'), (3, 'Await information'), (4, 'Completed'), (5, 'Follow up'), (6, 'In progress'), (7, 'Lodged - ATO to file'), (8, 'To invoice something')], null=True),
        ),
    ]
